[tool.poetry]
name = "pycoingecko_extra"
version = "1.0.0"
description = "An extension of the pycoingecko api client that introduces extra functionality like handling rate limiting and pagination."
authors = ["Bryce Morrow <brycemorrow4564@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/brycemorrow4564/pycoingecko-extra"
repository = "https://github.com/brycemorrow4564/pycoingecko-extra"
packages = [
    { include = "pycoingecko_extra" }, 
    { include = "tests" }
]
exclude = ["tests"]

[tool.poetry.scripts]                                                           
test = "tests.scripts.runner:run_tests"  
get_data = "tests.scripts.get_test_data:get_data"

[tool.poetry.dependencies]
python = "^3.7"
pycoingecko = "*"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
responses = "^0.16.0"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
black = {version = "^21.12b0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
