[tool.poetry]
name = "py_coingecko"
version = "1.0.0"
description = "An extension of the pycoingecko api client that introduces extra functionality like handling rate limiting and pagination."
authors = ["Bryce Morrow <brycemorrow4564@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/brycemorrow4564/pycoingecko-extra"
repository = "https://github.com/brycemorrow4564/pycoingecko-extra"
packages = [
    { include = "py_coingecko" }, 
    { include = "tests" }, 
    { include = "scripts" }, 
    { include = "swagger_client", from = "swagger_generated" }
]
exclude = ["tests", "scripts"]

[tool.poetry.scripts]                                                           
test = "tests.scripts.runner:run_tests"  
get_data = "tests.scripts.get_test_data:get_data"
generate_client = "scripts.swagger:generate_client" 
generate_test_data = "scripts.swagger:generate_test_data" 
generate_test_data_template = "scripts.swagger:generate_test_data_template"
get_cov = "scripts.github:get_cov_percent"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.27.1"
python-dotenv = "^0.19.2"
swagger_client = { path = "./swagger_generated", develop = true } 

[tool.poetry.dev-dependencies]
responses = "^0.16.0"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
black = {version = "^21.12b0", allow-prereleases = true }
toml = "^0.10.2"
deepdiff = "^5.7.0"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools"]
build-backend = "poetry.core.masonry.api"
